name: Build MapUnlocker

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4

    - name: Setup Vcpkg
      uses: lukka/run-vcpkg@v11
      with:
        vcpkgJsonGlob: 'vcpkg.json'

    - name: Install nlohmann-json
      run: |
        vcpkg install nlohmann-json --triplet x64-windows
        vcpkg integrate install
      shell: cmd

    - name: Download ARK API
      run: |
        curl -L https://github.com/Michidu/ARK-Server-API/releases/download/v3.54/ArkApi_3.54.zip -o arkapi.zip
        unzip arkapi.zip -d arkapi
        mkdir -p ArkApi/Includes/API/ARK
        curl -L https://raw.githubusercontent.com/Michidu/ARK-Server-API/v3.54/include/API/ARK/Ark.h -o ArkApi/Includes/API/ARK/Ark.h
      shell: cmd

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v2
      with:
        vs-version: '17.0'

    - name: Build Plugin
      run: |
        cl /LD /EHsc /I"ArkApi/Includes" /I"vcpkg_installed/x64-windows/include" MapUnlocker/MapUnlocker.cpp /Fe:MapUnlocker/bin/Release/MapUnlocker.dll
      shell: cmd

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: MapUnlocker
        path: MapUnlocker/bin/Release/MapUnlocker.dll