name: Build MapUnlocker

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    env:
      VCPKG_ROOT: ${{ github.workspace }}\vcpkg
      ARKAPI_VERSION: "3.54"

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    # 安装 vcpkg
    - name: Setup vcpkg
      uses: lukka/run-vcpkg@v11
      with:
        vcpkgJsonGlob: 'vcpkg.json'

    # 安装依赖
    - name: Install Dependencies
      shell: cmd
      run: |
        vcpkg install --triplet x64-windows
        vcpkg integrate install

    # 下载 ArkApi release zip
    - name: Download ArkApi
      shell: cmd
      run: |
        curl -L https://github.com/Michidu/ARK-Server-API/releases/download/v%ARKAPI_VERSION%/ArkApi_%ARKAPI_VERSION%.zip -o arkapi.zip
        powershell -Command "Expand-Archive arkapi.zip -DestinationPath arkapi"
        mkdir ArkApi\Includes\API\ARK
        curl -L https://raw.githubusercontent.com/ServersHub/Framework-ArkServerApi/v%ARKAPI_VERSION%/include/API/ARK/Ark.h -o ArkApi\Includes\API\ARK\Ark.h
        mkdir ArkApi\Libs
        xcopy arkapi\Libs\* ArkApi\Libs\ /s /y

    # 编译 MapUnlocker.dll
    - name: Build Plugin
      shell: cmd
      run: |
        mkdir MapUnlocker\bin\Release
        call "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvars64.bat"
        cl /LD /EHsc ^
           /I"ArkApi/Includes" ^
           /I"vcpkg_installed/x64-windows/include" ^
           MapUnlocker\MapUnlocker.cpp ^
           /link /LIBPATH:"ArkApi\Libs" ArkApi.lib ^
           /OUT:MapUnlocker\bin\Release\MapUnlocker.dll

    # 上传生成的 DLL
    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: MapUnlocker
        path: MapUnlocker/bin/Release/MapUnlocker.dll
